openapi: 3.1.0
info:
  title: Logbook
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
tags:
  - name: Rides
paths:
  /rides:
    get:
      summary: GetRides
      tags:
        - Rides
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RideCollection'
              examples:
                success:
                  value:
                    items:
                      - apid: 0psH9HJ
                        destination: Pardubice
                        date: '2022-01-09'
                        distance: 82.8
                        carId: s906u8s
        '500':
          $ref: '#/components/responses/InternalServerError'
      operationId: GetRides
      parameters:
        - schema:
            type: string
            pattern: '^[a-z0-9]{7}$'
            minLength: 7
            maxLength: 7
            example: lo9ui67
          in: query
          name: carId
          description: APID vozidla
      description: Vrací seznam jízd s ohledem na filtr
    post:
      summary: CreateRide
      operationId: CreateRide
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ride'
              examples:
                success:
                  value:
                    apid: 0psh9jh
                    destination: Pardubice
                    date: '2022-01-09'
                    distance: 82.8
                    carId: s906u8s
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RideCreate'
            examples:
              valid-request:
                value:
                  destination: Praha
                  date: '2022-05-19'
                  distance: 18.9
                  carId: p9os76h
        description: ''
      tags:
        - Rides
      parameters:
        - schema:
            type: string
            example: 888a360a-114d-4bac-8726-d87d58900f20
          in: header
          name: idempotency-key
          description: Klíč pro zajištění idempotentnosti
      description: Vytvoření nové jízdy v knize jízd.
  '/rides/{id}':
    parameters:
      - schema:
          type: string
          pattern: '^[a-z0-9]{7}$'
          minLength: 7
          maxLength: 7
        name: id
        in: path
        required: true
        description: APID jízdy
    get:
      summary: GetRideById
      tags:
        - Rides
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ride'
              examples:
                success:
                  value:
                    apid: 0psH9HJ
                    destination: Pardubice
                    date: '2022-01-09'
                    distance: 82.8
                    carId: s906u8s
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
      operationId: GetRideById
      description: Vrácení detailů jízdy dle APID
  /auth/token:
    post:
      summary: ''
      operationId: CreateAuthToken
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
              examples:
                success:
                  value:
                    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                    expires: '2019-08-24T14:15:22Z'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Credentials'
            examples:
              valid-request:
                value:
                  username: johndoe
                  password: sk8ksjdld**s!d
      description: Vystaví token na základě úspěšného ověření uživatele
components:
  schemas:
    RideCollection:
      title: RideCollection
      type: object
      description: Model reprezentuje seznam jízdy
      properties:
        items:
          type: array
          description: Seznam jízd odpovídajících požadavku
          maxItems: 100
          items:
            $ref: '#/components/schemas/Ride'
    RideCreate:
      type: object
      title: RideCreate
      description: Model pro vytváření nové jízdy v knize jízd
      properties:
        destination:
          type: string
          maxLength: 100
          description: Cíl jízdy
          example: Praha
        date:
          type: string
          format: date
          description: Datum jízdy
          example: '2022-05-19'
        distance:
          type: number
          format: double
          minimum: 0
          description: Vzdálenost v kilometrech
          example: 18.9
        carId:
          type: string
          minLength: 7
          maxLength: 7
          pattern: '^[a-z0-9]{7}$'
          description: APID vozidla
          example: p9os76h
      required:
        - destination
        - date
        - distance
        - carId
    Ride:
      type: object
      title: Ride
      description: Jedna jízda z knihy jízd
      properties:
        apid:
          type: string
          minLength: 7
          maxLength: 7
          pattern: '^[a-z0-9]{7}$'
          description: APID jízdy
          example: 0psH9HJ
        destination:
          type: string
          maxLength: 100
          description: Cíl jízdy
          example: Pardubice
        date:
          type: string
          format: date
          description: Datum uskutečnění jízdy
          example: '2022-01-09'
        distance:
          type: number
          format: double
          minimum: 0
          description: Vzdálenost v kilometrech
          example: 82.8
        carId:
          type: string
          pattern: '^[a-z0-9]{7}$'
          minLength: 7
          maxLength: 7
          description: APID vozidla
          example: s906u8s
    AuthToken:
      title: AuthToken
      type: object
      description: Autentizační token s identitou uživatele (ID token / JWT)
      properties:
        token:
          type: string
          description: JWT token
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        expires:
          type: string
          format: date-time
          description: Expirace tokenu (platnost)
    Credentials:
      title: Credentials
      type: object
      description: Model pro ověření uživatele na základě jména a hesla
      properties:
        username:
          type: string
          description: Uživatelské jméno
          example: johndoe
        password:
          type: string
          description: Heslo
          example: sk8ksjdld**s!d
    ProblemDetails:
      title: ProblemDetails
      type: object
      description: Generická chybová struktura pro většinu HTTP status kódů
      properties:
        type:
          type: string
          format: uri
          description: Druh chyby a odkaz na detaily (URL)
          example: 'https://www.restapi.cz/probs/problem-details'
        status:
          type: integer
          minimum: 400
          maximum: 599
          description: 'Stavový kód, koresponduje s HTTP Status Code'
          example: 500
        title:
          type: string
          description: Statický název chyby
          example: Internal Server Error
        detail:
          type: string
          description: Detailní informace k chybě
          example: '---'
    ValidationProblemDetails:
      title: ProblemDetails
      type: object
      description: 'Specifická chybová struktura obsahující kolekci validačních chyb, obvykle používaná se stavovým kódem 400'
      properties:
        type:
          type: string
          description: Druh chyby a odkaz na detaily (URL)
          format: uri
          example: 'https://www.restapi.cz/probs/validation-problem-details'
        status:
          type: integer
          minimum: 400
          maximum: 599
          example: 400
        title:
          type: string
          example: Validation Failed
        detail:
          type: string
          example: More information in errors property
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ValidationFailure'
    ValidationFailure:
      title: ValidationFailure
      type: object
      description: Detail validační chyby obsahující název validované vlastnosti a chybovou zprávu
      properties:
        propertyName:
          type: string
          description: Název validované vlastnosti
          example: Destination
        errorMessage:
          type: string
          description: Popis validační chyby
          example: Destination field is required!
  responses:
    BadRequest:
      description: Chyba vzniklá na základě neúspěšné validace nebo nevalidního požadavku
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationProblemDetails'
          examples:
            bad-request:
              value:
                type: 'https://www.restapi.cz/probs/validation-problem-details'
                status: 400
                title: Validation Failed
                detail: More information in errors property
                errors:
                  - propertyName: Destination
                    errorMessage: Destination field is required!
    NotFound:
      description: Požadovaný resource nebyl nalezen. Může se jednat o neexistující URL nebo konkrétní instanci objektu na základě neexistujícího identifikátoru.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          examples:
            not-found:
              value:
                type: 'https://www.restapi.cz/probs/problem-details'
                status: 404
                title: Resource Not Found
                detail: Resource with request APID does not exists!
    InternalServerError:
      description: 'Obecná chyba serveru. Server požadavek přijal, ale nebyl schopen jej zpracovat z důvodu vzniku neočekávané chyby.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          examples:
            internal-server-error:
              value:
                type: 'https://www.restapi.cz/probs/problem-details'
                status: 500
                title: Internal Server Error
                detail: '---'
